### ISSUE TITLE
Error when train VGG FSSD

### ISSUE THREAD

**Issue by JesseYang** [lzx1413/PytorchSSD#10]
I follow the instructions to train a VGG_FSSD model. An error occurred [here](https://github.com/lzx1413/PytorchSSD/blob/cd5776d7dd348f9c6a996cec8accf749e0bffee0/layers/modules/multibox_loss.py#L96):

`RuntimeError: The shape of the mask [8, 11620] at index 0 does not match the shape of the indexed tensor [92960, 1] at index 0`

It seems that a tensor with shape [92960, 1] cannot be indexed by a tensor with shape [8, 11620], even if the total number of elements for this two tensors are the same. The version of pytorch I used is 0.4.0.

**Comment by lzx1413** [comment]
You can try to append a view to reshape the tensor  to match the shapes. I haven't  test the project on pytorch0.4.

**Comment by JesseYang** [comment]
Thanks!
