### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by XN-0808** [lzx1413/PytorchSSD#100]
@lzx1413 
非常感谢您的工作．我最近在跑代码训练时碰到了一个问题，如下面截图所示：我运行的是FSSD-512，运行环境是pytorch0.4.1，在修改了几个常见的问题后，代码能够跑起来，但是我发现在每次验证测试集的时候都会报错，这个原因我发现是在向/home/shawn/PycharmProjects/PytorchSSD/data/VOCdevkit/results/VOC2007/Main文件夹中写入comp4_det_test_aeroplane.txt等文件的时候，有些txt文件中是空的，导致测试阶段会出现这个问题，请问出现这个原因是什么呢，该如何解决这个问题？

![image](https://user-images.githubusercontent.com/41976971/72197315-d09ef200-345a-11ea-8da3-bea91f59d88a.png)

**Comment by chaitanyarit** [comment]
@XN-0808 How did you solve this problem?
