### ISSUE TITLE
mAP result of FSSD-MobileNet on VOC2007

### ISSUE THREAD

**Issue by insmod-he** [lzx1413/PytorchSSD#11]
Hi, Zuo-xin:

Thanks for your nice job. 
 I have trained a model with the following script and got a 73.84 mAP score. However it seems that my mAP score is much lower than [this](https://github.com/ShuangXieIrene/ssds.pytorch) (78.4% mAP). 
Could you give me some suggestions?

```shell
python train_test_fssd_mobile_pre.py \
    --version 'FSSD_mobile' \
    --size 300 \
    --dataset VOC \
    --basenet 'weights/mobilenet_1.pth' \
    --jaccard_threshold 0.5 \
    --batch_size 32 \
    --num_workers 4 \
    --cuda True \
    --lr 4e-3 \
    --momentum 0.9 \
    --warm_epoch 4 \
    --weight_decay 5e-4 \
    --gamma 0.1 \
    --log_iters True \
    --save_folder 'output/VOC_FSSD_MobileNet' \
    --date '05-12-2018' \
    --save_frequency 40 \
    --test_frequency 10 \
    --send_images_to_visdom False
```

**Comment by lzx1413** [comment]
I have the same result with you. I guess the result in that repo is after being pretrained with COCO.

**Comment by insmod-he** [comment]
OK, I'm going to confirm this with the author of that repo.

**Comment by lzx1413** [comment]
BN layer is frozen is faster rcnn because of the small batchsize and memory limitation of GPU. SSDS usually do not do this actually.

**Comment by insmod-he** [comment]
I know what you mean. However, the BN layer is frozen in the original Caffe edition SSD. Please refer to the code [here](https://github.com/weiliu89/caffe/blob/ssd/python/caffe/model_libs.py#L46).
In fact I'm training a SSD-MobileNet model whose BN layers are frozen. Unfortunately, the current performance is poor.

**Comment by insmod-he** [comment]
I find that set the 'learn_mult' and 'decay_mult' to 0 will NOT freeze the BN layer. The correct approach is to set 'use_global_status=true' in Caffe. So the original SSD implementation actually do not freeze BN layer.

**Comment by fanbinqi** [comment]
> Hi, Zuo-xin:
> 
> Thanks for your nice job.
> I have trained a model with the following script and got a 73.84 mAP score. However it seems that my mAP score is much lower than [this](https://github.com/ShuangXieIrene/ssds.pytorch) (78.4% mAP).
> Could you give me some suggestions?
> 
> ```shell
> python train_test_fssd_mobile_pre.py \
>     --version 'FSSD_mobile' \
>     --size 300 \
>     --dataset VOC \
>     --basenet 'weights/mobilenet_1.pth' \
>     --jaccard_threshold 0.5 \
>     --batch_size 32 \
>     --num_workers 4 \
>     --cuda True \
>     --lr 4e-3 \
>     --momentum 0.9 \
>     --warm_epoch 4 \
>     --weight_decay 5e-4 \
>     --gamma 0.1 \
>     --log_iters True \
>     --save_folder 'output/VOC_FSSD_MobileNet' \
>     --date '05-12-2018' \
>     --save_frequency 40 \
>     --test_frequency 10 \
>     --send_images_to_visdom False
> ```

I haven't achieve the map to 73.84, could you tell the training strategy? Thanks a lot!
