### ISSUE TITLE
AttributeError: 'SSD' object has no attribute 'module'

### ISSUE THREAD

**Issue by Wondersui** [lzx1413/PytorchSSD#12]
APs, mAP = test_net(test_save_dir, net, detector, args.cuda, testset,
                                        BaseTransform(net.module.size, rgb_means, rgb_std, (2, 0, 1)),
                                        top_k, thresh=0.01)
Traceback (most recent call last):
  File "/home/suizhehao/pytorch_detect/PytorchSSD/train_test.py", line 484, in <module>
    train()
  File "/home/suizhehao/pytorch_detect/PytorchSSD/train_test.py", line 291, in train
    BaseTransform(net.module.size, rgb_means, rgb_std, (2, 0, 1)),
  File "/home/suizhehao/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'SSD' object has no attribute 'module'
what is the problem?

**Comment by lzx1413** [comment]
You can replace net.module.size with net.size. Module will be added if you train the network with multi-gpus.

**Comment by Wondersui** [comment]
I have solved it,thank you^ ^

**Comment by Wondersui** [comment]
I have another problem,when I use the train_test.py to train the voc dataset,it will stop in the Epoch3

Epoch:3 || epochiter: 1974/2068|| Totel iter 6110 || L: 1.5484 C: 3.7036||Batch time: 0.4011 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 1984/2068|| Totel iter 6120 || L: 1.4901 C: 3.6711||Batch time: 0.4020 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 1994/2068|| Totel iter 6130 || L: 1.4994 C: 3.7394||Batch time: 0.4352 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 2004/2068|| Totel iter 6140 || L: 1.6116 C: 3.2869||Batch time: 0.4009 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 2014/2068|| Totel iter 6150 || L: 1.5345 C: 3.8280||Batch time: 0.3992 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 2024/2068|| Totel iter 6160 || L: 1.4239 C: 3.6214||Batch time: 0.4073 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 2034/2068|| Totel iter 6170 || L: 1.5346 C: 3.4771||Batch time: 0.4425 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 2044/2068|| Totel iter 6180 || L: 1.4747 C: 3.6433||Batch time: 0.4029 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 2054/2068|| Totel iter 6190 || L: 1.5019 C: 3.6043||Batch time: 0.4037 sec. ||LR: 0.00050000
Epoch:3 || epochiter: 2064/2068|| Totel iter 6200 || L: 1.3754 C: 3.5850||Batch time: 0.3989 sec. ||LR: 0.00050000

like this,it can not go on.what is the problem about this?

**Comment by Wondersui** [comment]
I used the pytorch 0.3.1 to run the code.

**Comment by lzx1413** [comment]
@Wondersui 
add
```
import cv2
cv2.setNumThreads(0)  # pytorch issue 1355: possible deadlock in dataloader
```
may solve the problem
