### ISSUE TITLE
How to determine the parameters in file  /data/config.py ?

### ISSUE THREAD

**Issue by xiaozhi2015** [lzx1413/PytorchSSD#19]
Hello thank you for sharing your codes.
How to determine the parameters in file /data/config.py , especially "min_sizes" & "max_sizes" of VOC & COCO.
Much thx! @lzx1413

**Comment by xiaozhi2015** [comment]
Obtain these parameters from original Caffe_SSD prototxt directly ?

**Comment by lzx1413** [comment]
You can set these parameters by yourself.There are no fixed values

**Comment by xiaozhi2015** [comment]
But these parameters represent default prior boxes, default prior boxes in VOC & COCO are different. The author of SSD seems to determine different prior boxes for diffrernt dataset,  especially "min_sizes" & "max_sizes". Your opinion?
3q!

**Comment by xiaozhi2015** [comment]
But these parameters represent default prior boxes, default prior boxes in VOC & COCO are different. The author of SSD seems to determine different prior boxes for diffrernt dataset, especially "min_sizes" & "max_sizes". Your opinion?
3q! @lzx1413

**Comment by lzx1413** [comment]
I think the anchor size should be considered according to the object distribution.
