### ISSUE TITLE
Error while reshaping tensor, in the model definition.

### ISSUE THREAD

**Issue by kirnh** [lzx1413/PytorchSSD#20]
RuntimeError: invalid argument 2: size '[2 x -1 x 81]' is invalid for input with 267750 elements at /pytorch/aten/src/TH/THStorage.c:37

I get this error when I try to run the refinedet_train_test.py script! My input image size is 320. I don't understand where in the pipeline the source of the shape mismatch is. I haven't changed any of the code. It'd be great to know if someone faced this, or if I'm doing something wrong.
Thanks!

**Comment by lzx1413** [comment]
I haven't met this error while training on voc dataset.

**Comment by kirnh** [comment]
Thanks for replying so quickly. I'm using the COCO dataset. So, you think something is wrong with the dataset?

**Comment by strongwolf** [comment]
Did you get the expected accuracy on coco dataset?

**Comment by foralliance** [comment]
@kirnh  have u solved the problem??
