### ISSUE TITLE
mAP of yolov2

### ISSUE THREAD

**Issue by marvis** [lzx1413/PytorchSSD#23]
Hi @lzx1413,

I am just curious about the mAP of yolov2, it is extremely high. Can you tell me how do you ge this mAP value?

YOLOv2 (Darknet-19) | 78.6

Best,

**Comment by lzx1413** [comment]
I did not train yolov 2 by myself in this repo. How do you know this result ?

**Comment by marvis** [comment]
It is in your readme.

System | mAP | FPS (Titan X Maxwell)
-- | -- | --
Faster R-CNN (VGG16) | 73.2 | 7
YOLOv2 (Darknet-19) | 78.6 | 40
R-FCN (ResNet-101) | 80.5 | 9
SSD300* (VGG16) | 77.2 | 46
SSD512* (VGG16) | 79.8 | 19
RFBNet300 (VGG16) | 80.5 | 83
RFBNet512 (VGG16) | 82.2 | 38
SSD300 (VGG) | 77.8 | 150 (1080Ti)
FSSD300 (VGG)

**Comment by lzx1413** [comment]
It is cited from paper yolo9000
