### ISSUE TITLE
 what does s1 and s2 means?  

### ISSUE THREAD

**Issue by isalirezag** [lzx1413/PytorchSSD#29]
In the papers it says:
'subsample parameters from fc6 and fc7, changepool5 from2×2−s2to3×3−s1'
Can you please tell me what does it mean by s1 and s2?

also we can see `3x3x512-s2` and `3x3x256-s1` in the following figure
![image](https://user-images.githubusercontent.com/12434910/43351282-9f15c68a-91dd-11e8-97bb-fb7152369471.png)

**Comment by lzx1413** [comment]
It mean the stride of the convolutional layer
