### ISSUE TITLE
SSD为什么去掉了batch_norm层

### ISSUE THREAD

**Issue by dongfengxijian** [lzx1413/PytorchSSD#30]
我看你的SSD实现代码中没有使用batch_norm层，我想问一下为什么这么做，有什么好处吗？

**Comment by lzx1413** [comment]
因为caffe版本的也没加，一般如果基础模型是有bn的后面才会加

**Comment by dongfengxijian** [comment]
@lzx1413  先感谢你的解答。
下面是另外一个问题：
`mbox = {
    '300': [6, 6, 6, 6, 4, 4],  # number of boxes per feature map location
    '512': [6, 6, 6, 6, 6, 4, 4],
}`
我看到论文中SSD300mbox是[4, 6, 6, 6, 4, 4]。你这段代码中第一个取6是为了提高mPa吗？

**Comment by dongfengxijian** [comment]
@lzx1413 哦，谢谢指导
