### ISSUE TITLE
关于fps的问题

### ISSUE THREAD

**Issue by dongfengxijian** [lzx1413/PytorchSSD#32]
首先，想确认一下表中的fps是通过1/detect_time求出的吗？其次，我用1080ti跑了SSD300达不到150fps，大概只有83.3fps，想问一下原因。希望大神能指导一下

**Comment by lzx1413** [comment]
如果imshow或者存图结果的话速度会慢，直接测试网络就很快了

**Comment by qinziqiao** [comment]
@dongfengxijian  请问你怎么测试FPS的？ 计算detect_time只计算图片放网络里跑和NMS的时间吗
