### ISSUE TITLE
关于训练集07++12+COCO上训练

### ISSUE THREAD

**Issue by dongfengxijian** [lzx1413/PytorchSSD#38]
在训练集07++12+COCO上训练时，是直接将COCO的训练好的模型作为预训练模型，再在07++12上训练吗？还是需要做其他处理吗？

**Comment by lzx1413** [comment]
将coco训练好的模型进行权重抽取之后用来初始化voc的模型

**Comment by dongfengxijian** [comment]
@lzx1413 权重抽取怎么做？

**Comment by dongfengxijian** [comment]
@lzx1413 嗯，十分期待
