### ISSUE TITLE
我想请问COCO的检测结果怎么提交到服务器上去 

### ISSUE THREAD

**Issue by dongfengxijian** [lzx1413/PytorchSSD#41]
我用跑了COCO数据集test—dev的结果想提交服务器上测评，但是upload fail。我想请教一下这方面的问题

**Comment by lxy5513** [comment]
得到一个json文件，将其转为zip文件后，在COCO官网注册后进行提交。2019和2017的test-dev数据集未发生变动，所以直接提交即可，大约10-20分钟出结果，有时比较慢，提交不上多提交两遍即可。

**Comment by dongfengxijian** [comment]
> 得到一个json文件，将其转为zip文件后，在COCO官网注册后进行提交。2019和2017的test-dev数据集未发生变动，所以直接提交即可，大约10-20分钟出结果，有时比较慢，提交不上多提交两遍即可。

谢谢老哥指点，我后面成功提交了。
