### ISSUE TITLE
RuntimeError:shape does not match when I train Refinedet in both 0.4 branch and master branch

### ISSUE THREAD

**Issue by lc17721825** [lzx1413/PytorchSSD#55]
Traceback (most recent call last):
  File "refinedet_train_test.py", line 448, in <module>
    train()
  File "refinedet_train_test.py", line 310, in train
    arm_loss_l,arm_loss_c = arm_criterion((arm_loc,arm_conf),priors,targets)
  File "/home/lc/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lc/git/pytorch_project/PytorchSSD/layers/modules/refine_multibox_loss.py", line 112, in forward
    loss_c[pos] = 0 # filter out pos boxes for now
RuntimeError: The shape of the mask [32, 6375] at index 0 does not match the shape of the indexed tensor [204000, 1] at index 0
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7faf15a9bfd0>> ignored

Thanks in advance. @lzx1413

**Comment by lc17721825** [comment]
I have solved this problem, you can see the solution in ssd.pytorch in github

**Comment by foralliance** [comment]
@lc17721825 
能否给出一个链接

**Comment by lc17721825** [comment]
https://github.com/amdegroot/ssd.pytorch/issues/173

**Comment by lc17721825** [comment]
@foralliance

**Comment by foralliance** [comment]
@lc17721825  
thks
