### ISSUE TITLE
The shape of the mask [32, 6375] at index 0 does not match the shape of the indexed tensor [204000, 1] at index 0

### ISSUE THREAD

**Issue by xxlei** [lzx1413/PytorchSSD#61]
File "/home/lei/PytorchSSD/layers/modules/refine_multibox_loss.py", line 112, in forward
    loss_c[pos] = 0  # filter out pos boxes for now
RuntimeError: The shape of the mask [32, 6375] at index 0 does not match the shape of the indexed tensor [204000, 1] at index 0

**Comment by WangTianYuan** [comment]
@xxlei 你好，我遇到了你一样的问题，请问怎么解决的？

**Comment by csm-kr** [comment]
me too!

**Comment by BaoXiaoyi1999** [comment]
Exchange the 97, 98 lines in layers/module/multibox_loss.py may help. At least it works for me.
