### ISSUE TITLE
Is rgb_std = (1,1,1) in train_test.py right?

### ISSUE THREAD

**Issue by beckhamchen** [lzx1413/PytorchSSD#63]
In train_test.py:
rgb_std = (1, 1, 1) while
rgb_means = (103.94, 116.78, 123.68)

But in train_test_fssd_mobile_pre.py
rgb_means = (255 * 0.485, 255 * 0.456, 255 * 0.406)
rgb_std = (0.229 * 255, 0.224 * 255, 0.255 * 255)

the two rgt_std are far away.
I think rgb_std in train_test.py is not right. Anybody kown ?

**Comment by lzx1413** [comment]
The mean and std are same with the pretrained model. For vgg, we aodpt the model from caffe. For mobilenet, we adopt the model which is trained with pytorch.
