### ISSUE TITLE
A problem with Multi-Scale test

### ISSUE THREAD

**Issue by WangTianYuan** [lzx1413/PytorchSSD#76]
I've successfully performed your project, but the test is only in one scale.
In the paper, they all have multi-scale test result, so I want to perform multi-scale test
But I don't know how to do this, do you have the code of multi-scale test? Or can you tell me how to achieve this? Thank you very much.

**Comment by lzx1413** [comment]
you can refer to this code https://github.com/sfzhang15/RefineDet/blob/master/test/refinedet_test.py
