### ISSUE TITLE
How to specify a gpu to train?

### ISSUE THREAD

**Issue by sagittahjz** [lzx1413/PytorchSSD#81]
I have tried the following codes

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "6"

torch.cuda.set_device(6)

but it always used GPU0

**Comment by sagittahjz** [comment]
use CUDA_VISIBLE_DEVICES=6 in the beginning of the train.sh is useful

but why the other ways I mentioned were useless?

**Comment by sagittahjz** [comment]
attach CUDA_VISIBLE_DEVICES=6 to the beginning of train.sh is useful

but why the other ways I mentioned were useless?

**Comment by lzx1413** [comment]
It is the problem of pytorch that always use the first gpu as the master gpu.
