### ISSUE TITLE
ImportError: cannot import name '_mask' from 'pycocotools'

### ISSUE THREAD

**Issue by CS-Jackson** [lzx1413/PytorchSSD#84]
Hi, @lzx1413 . When I run the train_test.py, this error occurs. I have run the make.sh and it seems work. So can you give me some advice? I run the code in anaconda3's virtual env, python=3.5, pytorch=0.4.1, cuda9.0

**Comment by CS-Jackson** [comment]
Good news. I have solved this problem.

**Comment by liu52020** [comment]
How did you solve it?
