### ISSUE TITLE
Hi, I need your help ! RefineDet320 voc 2007 only get mAP=0.76, lower than SSD300?

### ISSUE THREAD

**Issue by espectre** [lzx1413/PytorchSSD#88]

**Comment by yyx1107** [comment]
Have you resolved the problem?

**Comment by espectre** [comment]
@yyx1107  This repo may get better perfomance. And I have turn to RFBNet.

**Comment by yyx1107** [comment]
@espectre  Thanks for your reply~You use the RFBNet method of this repo and get good result, right?

**Comment by espectre** [comment]
@yyx1107 The author has open source.
